### ISSUE TITLE
Date of Birth not correct in export

### ISSUE THREAD

**Issue by Jecho66nl** [Zach417/churchetto-web#27]
After you have input the correct date of birth and saved it, you go to the export option.
When you see the result, every date of birth is running behind 1 day.
So if the date of birth is 06/14/1966, in the export overview you see the date of birth 06/13/1966

**Comment by Zach417** [comment]
I've made some changes to the way dates are handled. It probably has something to do with UTC and time zones. Try deleting/re-entering the birthdate and then run the export again to see if it's been fixed.

I've tested on my end that it's working correctly with the latest changes. It's possible it's still incorrect given the time zone differences. I'm going to go ahead and close this out since it's an older issue -- but if you test again and verify that it's not working correctly any more, I'll re-open it.
